#
# Copyright (C) 2014-2018 Pico Technology Ltd. See LICENSE file for terms.
#
"""
Defines the PICO_STATUS values defined in the PicoStatus.h C header file.
"""

PICO_STATUS = dict()
PICO_STATUS["PICO_OK"] = 0x00000000  # The PicoScope is functioning correctly.
PICO_STATUS["PICO_MAX_UNITS_OPENED"] = 0x00000001  # An attempt has been made to open more than <API>_MAX_UNITS.
PICO_STATUS["PICO_MEMORY_FAIL"] = 0x00000002  # Not enough memory could be allocated on the host machine.
PICO_STATUS["PICO_NOT_FOUND"] = 0x00000003  # No Pico Technology device could be found.
PICO_STATUS["PICO_FW_FAIL"] = 0x00000004  # Unable to download firmware.
PICO_STATUS["PICO_OPEN_OPERATION_IN_PROGRESS"] = 0x00000005  # The driver is busy opening a device.
PICO_STATUS["PICO_OPERATION_FAILED"] = 0x00000006  # An unspecified failure occurred.
PICO_STATUS["PICO_NOT_RESPONDING"] = 0x00000007  # The PicoScope is not responding to commands from the PC.
PICO_STATUS["PICO_CONFIG_FAIL"] = 0x00000008  # The configuration information in the PicoScope is corrupt or missing.
PICO_STATUS["PICO_KERNEL_DRIVER_TOO_OLD"] = 0x00000009  # The picopp.sys file is too old to be used with the device driver.
PICO_STATUS["PICO_EEPROM_CORRUPT"] = 0x0000000A  # The EEPROM has become corrupt, so the device will use a default setting.
PICO_STATUS["PICO_OS_NOT_SUPPORTED"] = 0x0000000B  # The operating system on the PC is not supported by this driver.
PICO_STATUS["PICO_INVALID_HANDLE"] = 0x0000000C  # There is no device with the handle value passed.
PICO_STATUS["PICO_INVALID_PARAMETER"] = 0x0000000D  # A parameter value is not valid.
PICO_STATUS["PICO_INVALID_TIMEBASE"] = 0x0000000E  # The timebase is not supported or is invalid.
PICO_STATUS["PICO_INVALID_VOLTAGE_RANGE"] = 0x0000000F  # The voltage range is not supported or is invalid.
PICO_STATUS["PICO_INVALID_CHANNEL"] = 0x00000010  # The channel number is not valid on this device or no channels have been set.
PICO_STATUS["PICO_INVALID_TRIGGER_CHANNEL"] = 0x00000011  # The channel set for a trigger is not available on this device.
PICO_STATUS["PICO_INVALID_CONDITION_CHANNEL"] = 0x00000012  # The channel set for a condition is not available on this device.
PICO_STATUS["PICO_NO_SIGNAL_GENERATOR"] = 0x00000013  # The device does not have a signal generator.
PICO_STATUS["PICO_STREAMING_FAILED"] = 0x00000014  # Streaming has failed to start or has stopped without user request.
PICO_STATUS["PICO_BLOCK_MODE_FAILED"] = 0x00000015  # Block failed to start - a parameter may have been set wrongly.
PICO_STATUS["PICO_NULL_PARAMETER"] = 0x00000016  # A parameter that was required is NULL.
PICO_STATUS["PICO_ETS_MODE_SET"] = 0x00000017  # The current functionality is not available while using ETS capture mode.
PICO_STATUS["PICO_DATA_NOT_AVAILABLE"] = 0x00000018  # No data is available from a run block call.
PICO_STATUS["PICO_STRING_BUFFER_TO_SMALL"] = 0x00000019  # The buffer passed for the information was too small.
PICO_STATUS["PICO_ETS_NOT_SUPPORTED"] = 0x0000001A  # ETS is not supported on this device.
PICO_STATUS["PICO_AUTO_TRIGGER_TIME_TO_SHORT"] = 0x0000001B  # The auto trigger time is less than the time it will take to collect the pre-trigger data.
PICO_STATUS["PICO_BUFFER_STALL"] = 0x0000001C  # The collection of data has stalled as unread data would be overwritten.
PICO_STATUS["PICO_TOO_MANY_SAMPLES"] = 0x0000001D  # Number of samples requested is more than available in the current memory segment.
PICO_STATUS["PICO_TOO_MANY_SEGMENTS"] = 0x0000001E  # Not possible to create number of segments requested.
PICO_STATUS["PICO_PULSE_WIDTH_QUALIFIER"] = 0x0000001F  # A null pointer has been passed in the trigger function or one of the parameters is out of range.
PICO_STATUS["PICO_DELAY"] = 0x00000020  # One or more of the hold-off parameters are out of range.
PICO_STATUS["PICO_SOURCE_DETAILS"] = 0x00000021  # One or more of the source details are incorrect.
PICO_STATUS["PICO_CONDITIONS"] = 0x00000022  # One or more of the conditions are incorrect.
PICO_STATUS["PICO_USER_CALLBACK"] = 0x00000023  # The driver's thread is currently in the <API>Ready callback function and therefore the action cannot be carried out.
PICO_STATUS["PICO_DEVICE_SAMPLING"] = 0x00000024  # An attempt is being made to get stored data while streaming. Either stop streaming by calling <API>Stop, or use <API>GetStreamingLatestValues.
PICO_STATUS["PICO_NO_SAMPLES_AVAILABLE"] = 0x00000025  # Data is unavailable because a run has not been completed.
PICO_STATUS["PICO_SEGMENT_OUT_OF_RANGE"] = 0x00000026  # The memory segment index is out of range.
PICO_STATUS["PICO_BUSY"] = 0x00000027  # The device is busy so data cannot be returned yet.
PICO_STATUS["PICO_STARTINDEX_INVALID"] = 0x00000028  # The start time to get stored data is out of range.
PICO_STATUS["PICO_INVALID_INFO"] = 0x00000029  # The information number requested is not a valid number.
PICO_STATUS["PICO_INFO_UNAVAILABLE"] = 0x0000002A  # The handle is invalid so no information is available about the device. Only PICO_DRIVER_VERSION is available.
PICO_STATUS["PICO_INVALID_SAMPLE_INTERVAL"] = 0x0000002B  # The sample interval selected for streaming is out of range.
PICO_STATUS["PICO_TRIGGER_ERROR"] = 0x0000002C  # ETS is set but no trigger has been set. A trigger setting is required for ETS.
PICO_STATUS["PICO_MEMORY"] = 0x0000002D  # Driver cannot allocate memory.
PICO_STATUS["PICO_SIG_GEN_PARAM"] = 0x0000002E  # Incorrect parameter passed to the signal generator.
PICO_STATUS["PICO_SHOTS_SWEEPS_WARNING"] = 0x0000002F  # Conflict between the shots and sweeps parameters sent to the signal generator.
PICO_STATUS["PICO_SIGGEN_TRIGGER_SOURCE"] = 0x00000030  # A software trigger has been sent but the trigger source is not a software trigger. 
PICO_STATUS["PICO_AUX_OUTPUT_CONFLICT"] = 0x00000031  # An <API>SetTrigger call has found a conflict between the trigger source and the AUX output enable.
PICO_STATUS["PICO_AUX_OUTPUT_ETS_CONFLICT"] = 0x00000032  # ETS mode is being used and AUX is set as an input.
PICO_STATUS["PICO_WARNING_EXT_THRESHOLD_CONFLICT"] = 0x00000033  # Attempt to set different EXT input thresholds set for signal generator and oscilloscope trigger.
PICO_STATUS["PICO_WARNING_AUX_OUTPUT_CONFLICT"] = 0x00000034  # An <API>SetTrigger... function has set AUX as an output and the signal generator is using it as a trigger.
PICO_STATUS["PICO_SIGGEN_OUTPUT_OVER_VOLTAGE"] = 0x00000035  # The combined peak to peak voltage and the analog offset voltage exceed the maximum voltage the signal generator can produce.
PICO_STATUS["PICO_DELAY_NULL"] = 0x00000036  # NULL pointer passed as delay parameter.
PICO_STATUS["PICO_INVALID_BUFFER"] = 0x00000037  # The buffers for overview data have not been set while streaming.
PICO_STATUS["PICO_SIGGEN_OFFSET_VOLTAGE"] = 0x00000038  # The analog offset voltage is out of range.
PICO_STATUS["PICO_SIGGEN_PK_TO_PK"] = 0x00000039  # The analog peak-to-peak voltage is out of range.
PICO_STATUS["PICO_CANCELLED"] = 0x0000003A  # A block collection has been cancelled.
PICO_STATUS["PICO_SEGMENT_NOT_USED"] = 0x0000003B  # The segment index is not currently being used.
PICO_STATUS["PICO_INVALID_CALL"] = 0x0000003C  # The wrong GetValues function has been called for the collection mode in use.
PICO_STATUS["PICO_GET_VALUES_INTERRUPTED"] = 0x0000003D  
PICO_STATUS["PICO_NOT_USED"] = 0x0000003F  # The function is not available.
PICO_STATUS["PICO_INVALID_SAMPLERATIO"] = 0x00000040  # The aggregation ratio requested is out of range.
PICO_STATUS["PICO_INVALID_STATE"] = 0x00000041  # Device is in an invalid state.
PICO_STATUS["PICO_NOT_ENOUGH_SEGMENTS"] = 0x00000042  # The number of segments allocated is fewer than the number of captures requested.
PICO_STATUS["PICO_DRIVER_FUNCTION"] = 0x00000043  # A driver function has already been called and not yet finished. Only one call to the driver can be made at any one time.
PICO_STATUS["PICO_RESERVED"] = 0x00000044  # Not used
PICO_STATUS["PICO_INVALID_COUPLING"] = 0x00000045  # An invalid coupling type was specified in <API>SetChannel.
PICO_STATUS["PICO_BUFFERS_NOT_SET"] = 0x00000046  # An attempt was made to get data before a data buffer was defined.
PICO_STATUS["PICO_RATIO_MODE_NOT_SUPPORTED"] = 0x00000047  # The selected downsampling mode (used for data reduction) is not allowed.
PICO_STATUS["PICO_RAPID_NOT_SUPPORT_AGGREGATION"] = 0x00000048  # Aggregation was requested in rapid block mode.
PICO_STATUS["PICO_INVALID_TRIGGER_PROPERTY"] = 0x00000049  # An invalid parameter was passed to <API>SetTriggerChannelProperties.
PICO_STATUS["PICO_INTERFACE_NOT_CONNECTED"] = 0x0000004A  # The driver was unable to contact the oscilloscope.
PICO_STATUS["PICO_RESISTANCE_AND_PROBE_NOT_ALLOWED"] = 0x0000004B  # Resistance-measuring mode is not allowed in conjunction with the specified probe.
PICO_STATUS["PICO_POWER_FAILED"] = 0x0000004C  # The device was unexpectedly powered down.
PICO_STATUS["PICO_SIGGEN_WAVEFORM_SETUP_FAILED"] = 0x0000004D  # A problem occurred in <API>SetSigGenBuiltIn or <API>SetSigGenArbitrary.
PICO_STATUS["PICO_FPGA_FAIL"] = 0x0000004E  # FPGA not successfully set up.
PICO_STATUS["PICO_POWER_MANAGER"] = 0x0000004F  
PICO_STATUS["PICO_INVALID_ANALOGUE_OFFSET"] = 0x00000050  # An impossible analog offset value was specified in <API>SetChannel.
PICO_STATUS["PICO_PLL_LOCK_FAILED"] = 0x00000051  # There is an error within the device hardware.
PICO_STATUS["PICO_ANALOG_BOARD"] = 0x00000052  # There is an error within the device hardware.
PICO_STATUS["PICO_CONFIG_FAIL_AWG"] = 0x00000053  # Unable to configure the signal generator.
PICO_STATUS["PICO_INITIALISE_FPGA"] = 0x00000054  # The FPGA cannot be initialized, so unit cannot be opened.
PICO_STATUS["PICO_EXTERNAL_FREQUENCY_INVALID"] = 0x00000056  # The frequency for the external clock is not within 15% of the nominal value.
PICO_STATUS["PICO_CLOCK_CHANGE_ERROR"] = 0x00000057  # The FPGA could not lock the clock signal.
PICO_STATUS["PICO_TRIGGER_AND_EXTERNAL_CLOCK_CLASH"] = 0x00000058  # You are trying to configure the AUX input as both a trigger and a reference clock.
PICO_STATUS["PICO_PWQ_AND_EXTERNAL_CLOCK_CLASH"] = 0x00000059  # You are trying to congfigure the AUX input as both a pulse width qualifier and a reference clock.
PICO_STATUS["PICO_UNABLE_TO_OPEN_SCALING_FILE"] = 0x0000005A  # The requested scaling file cannot be opened.
PICO_STATUS["PICO_MEMORY_CLOCK_FREQUENCY"] = 0x0000005B  # The frequency of the memory is reporting incorrectly.
PICO_STATUS["PICO_I2C_NOT_RESPONDING"] = 0x0000005C  # The I2C that is being actioned is not responding to requests.
PICO_STATUS["PICO_NO_CAPTURES_AVAILABLE"] = 0x0000005D  # There are no captures available and therefore no data can be returned.
PICO_STATUS["PICO_NOT_USED_IN_THIS_CAPTURE_MODE"] = 0x0000005E  # The capture mode the device is currently running in does not support the current request.
PICO_STATUS["PICO_TOO_MANY_TRIGGER_CHANNELS_IN_USE"] = 0x0000005F  # The number of trigger channels is greater than 4, except for a PS4824 where 8 channels are allowed for rising/falling/rising_or_falling trigger directions.
PICO_STATUS["PICO_INVALID_TRIGGER_DIRECTION"] = 0x00000060  # When more than 4 trigger channels are set on a PS4824 and the direction is out of range. 
PICO_STATUS["PICO_INVALID_TRIGGER_STATES"] = 0x00000061  #  When more than 4 trigger channels are set and their trigger condition states are not <API>_CONDITION_TRUE.
PICO_STATUS["PICO_GET_DATA_ACTIVE"] = 0x00000103  
PICO_STATUS["PICO_IP_NETWORKED"] = 0x00000104  # The device is currently connected via the IP Network socket and thus the call made is not supported.
PICO_STATUS["PICO_INVALID_IP_ADDRESS"] = 0x00000105  # An incorrect IP address has been passed to the driver.
PICO_STATUS["PICO_IPSOCKET_FAILED"] = 0x00000106  # The IP socket has failed.
PICO_STATUS["PICO_IPSOCKET_TIMEDOUT"] = 0x00000107  # The IP socket has timed out.
PICO_STATUS["PICO_SETTINGS_FAILED"] = 0x00000108  # Failed to apply the requested settings.
PICO_STATUS["PICO_NETWORK_FAILED"] = 0x00000109  # The network connection has failed.
PICO_STATUS["PICO_WS2_32_DLL_NOT_LOADED"] = 0x0000010A  # Unable to load the WS2 DLL.
PICO_STATUS["PICO_INVALID_IP_PORT"] = 0x0000010B  # The specified IP port is invalid.
PICO_STATUS["PICO_COUPLING_NOT_SUPPORTED"] = 0x0000010C  # The type of coupling requested is not supported on the opened device. 
PICO_STATUS["PICO_BANDWIDTH_NOT_SUPPORTED"] = 0x0000010D  # Bandwidth limiting is not supported on the opened device.
PICO_STATUS["PICO_INVALID_BANDWIDTH"] = 0x0000010E  # The value requested for the bandwidth limit is out of range.
PICO_STATUS["PICO_AWG_NOT_SUPPORTED"] = 0x0000010F  # The arbitrary waveform generator is not supported by the opened device.
PICO_STATUS["PICO_ETS_NOT_RUNNING"] = 0x00000110  # Data has been requested with ETS mode set but run block has not been called, or stop has been called.
PICO_STATUS["PICO_SIG_GEN_WHITENOISE_NOT_SUPPORTED"] = 0x00000111  # White noise output is not supported on the opened device.
PICO_STATUS["PICO_SIG_GEN_WAVETYPE_NOT_SUPPORTED"] = 0x00000112  # The wave type requested is not supported by the opened device.
PICO_STATUS["PICO_INVALID_DIGITAL_PORT"] = 0x00000113  # The requested digital port number is out of range (MSOs only).
PICO_STATUS["PICO_INVALID_DIGITAL_CHANNEL"] = 0x00000114  # The digital channel is not in the range <API>_DIGITAL_CHANNEL0 to <API>_DIGITAL_CHANNEL15, the digital channels that are supported.
PICO_STATUS["PICO_INVALID_DIGITAL_TRIGGER_DIRECTION"] = 0x00000115  # The digital trigger direction is not a valid trigger direction and should be equal in value to one of the <API>_DIGITAL_DIRECTION enumerations.
PICO_STATUS["PICO_SIG_GEN_PRBS_NOT_SUPPORTED"] = 0x00000116  # Signal generator does not generate pseudo-random binary sequence.
PICO_STATUS["PICO_ETS_NOT_AVAILABLE_WITH_LOGIC_CHANNELS"] = 0x00000117  # When a digital port is enabled, ETS sample mode is not available for use.
PICO_STATUS["PICO_WARNING_REPEAT_VALUE"] = 0x00000118
PICO_STATUS["PICO_POWER_SUPPLY_CONNECTED"] = 0x00000119  # 4-channel scopes only: The DC power supply is connected.
PICO_STATUS["PICO_POWER_SUPPLY_NOT_CONNECTED"] = 0x0000011A  # 4-channel scopes only: The DC power supply is not connected.
PICO_STATUS["PICO_POWER_SUPPLY_REQUEST_INVALID"] = 0x0000011B  # Incorrect power mode passed for current power source.
PICO_STATUS["PICO_POWER_SUPPLY_UNDERVOLTAGE"] = 0x0000011C  # The supply voltage from the USB source is too low.
PICO_STATUS["PICO_CAPTURING_DATA"] = 0x0000011D  # The oscilloscope is in the process of capturing data.
PICO_STATUS["PICO_USB3_0_DEVICE_NON_USB3_0_PORT"] = 0x0000011E  # A USB 3.0 device is connected to a non-USB 3.0 port.
PICO_STATUS["PICO_NOT_SUPPORTED_BY_THIS_DEVICE"] = 0x0000011F  # A function has been called that is not supported by the current device.
PICO_STATUS["PICO_INVALID_DEVICE_RESOLUTION"] = 0x00000120  # The device resolution is invalid (out of range).
PICO_STATUS["PICO_INVALID_NUMBER_CHANNELS_FOR_RESOLUTION"] = 0x00000121  # The number of channels that can be enabled is limited in 15 and 16-bit modes. (Flexible Resolution Oscilloscopes only)
PICO_STATUS["PICO_CHANNEL_DISABLED_DUE_TO_USB_POWERED"] = 0x00000122  # USB power not sufficient for all requested channels.
PICO_STATUS["PICO_SIGGEN_DC_VOLTAGE_NOT_CONFIGURABLE"] = 0x00000123  # The signal generator does not have a configurable DC offset.
PICO_STATUS["PICO_NO_TRIGGER_ENABLED_FOR_TRIGGER_IN_PRE_TRIG"] = 0x00000124  # An attempt has been made to define pre-trigger delay without first enabling a trigger.
PICO_STATUS["PICO_TRIGGER_WITHIN_PRE_TRIG_NOT_ARMED"] = 0x00000125  # An attempt has been made to define pre-trigger delay without first arming a trigger.
PICO_STATUS["PICO_TRIGGER_WITHIN_PRE_NOT_ALLOWED_WITH_DELAY"] = 0x00000126  # Pre-trigger delay and post-trigger delay cannot be used at the same time.
PICO_STATUS["PICO_TRIGGER_INDEX_UNAVAILABLE"] = 0x00000127  # The array index points to a nonexistent trigger.
PICO_STATUS["PICO_AWG_CLOCK_FREQUENCY"] = 0x00000128
PICO_STATUS["PICO_TOO_MANY_CHANNELS_IN_USE"] = 0x00000129  # There are more 4 analog channels with a trigger condition set.
PICO_STATUS["PICO_NULL_CONDITIONS"] = 0x0000012A  # The condition parameter is a null pointer.
PICO_STATUS["PICO_DUPLICATE_CONDITION_SOURCE"] = 0x0000012B  # There is more than one condition pertaining to the same channel.
PICO_STATUS["PICO_INVALID_CONDITION_INFO"] = 0x0000012C  # The parameter relating to condition information is out of range.
PICO_STATUS["PICO_SETTINGS_READ_FAILED"] = 0x0000012D  # Reading the metadata has failed.
PICO_STATUS["PICO_SETTINGS_WRITE_FAILED"] = 0x0000012E  # Writing the metadata has failed.
PICO_STATUS["PICO_ARGUMENT_OUT_OF_RANGE"] = 0x0000012F  # A parameter has a value out of the expected range.
PICO_STATUS["PICO_HARDWARE_VERSION_NOT_SUPPORTED"] = 0x00000130  # The driver does not support the hardware variant connected.
PICO_STATUS["PICO_DIGITAL_HARDWARE_VERSION_NOT_SUPPORTED"] = 0x00000131  # The driver does not support the digital hardware variant connected.
PICO_STATUS["PICO_ANALOGUE_HARDWARE_VERSION_NOT_SUPPORTED"] = 0x00000132  # The driver does not support the analog hardware variant connected.
PICO_STATUS["PICO_UNABLE_TO_CONVERT_TO_RESISTANCE"] = 0x00000133  # Converting a channel's ADC value to resistance has failed.
PICO_STATUS["PICO_DUPLICATED_CHANNEL"] = 0x00000134  # The channel is listed more than once in the function call.
PICO_STATUS["PICO_INVALID_RESISTANCE_CONVERSION"] = 0x00000135  # The range cannot have resistance conversion applied.
PICO_STATUS["PICO_INVALID_VALUE_IN_MAX_BUFFER"] = 0x00000136  # An invalid value is in the max buffer.
PICO_STATUS["PICO_INVALID_VALUE_IN_MIN_BUFFER"] = 0x00000137  # An invalid value is in the min buffer.
PICO_STATUS["PICO_SIGGEN_FREQUENCY_OUT_OF_RANGE"] = 0x00000138  # When calculating the frequency for phase conversion, the frequency is greater than that supported by the current variant.
PICO_STATUS["PICO_EEPROM2_CORRUPT"] = 0x00000139  # The device's EEPROM is corrupt. Contact Pico Technology support: https://www.picotech.com/tech-support.
PICO_STATUS["PICO_EEPROM2_FAIL"] = 0x0000013A  # The EEPROM has failed.
PICO_STATUS["PICO_SERIAL_BUFFER_TOO_SMALL"] = 0x0000013B  # The serial buffer is too small for the required information.
PICO_STATUS["PICO_SIGGEN_TRIGGER_AND_EXTERNAL_CLOCK_CLASH"] = 0x0000013C  # The signal generator trigger and the external clock have both been set. This is not allowed.
PICO_STATUS["PICO_WARNING_SIGGEN_AUXIO_TRIGGER_DISABLED"] = 0x0000013D  # The AUX trigger was enabled and the external clock has been enabled, so the AUX has been automatically disabled.
PICO_STATUS["PICO_SIGGEN_GATING_AUXIO_NOT_AVAILABLE"] = 0x00000013E  # The AUX I/O was set as a scope trigger and is now being set as a signal generator gating trigger. This is not allowed.
PICO_STATUS["PICO_SIGGEN_GATING_AUXIO_ENABLED"] = 0x00000013F  # The AUX I/O was set by the signal generator as a gating trigger and is now being set as a scope trigger. This is not allowed.
PICO_STATUS["PICO_RESOURCE_ERROR"] = 0x00000140  # A resource has failed to initialise
PICO_STATUS["PICO_TEMPERATURE_TYPE_INVALID"] = 0x000000141  # The temperature type is out of range
PICO_STATUS["PICO_TEMPERATURE_TYPE_NOT_SUPPORTED"] = 0x000000142  # A requested temperature type is not supported on this device
PICO_STATUS["PICO_TIMEOUT"] = 0x00000143  # A read/write to the device has timed out
PICO_STATUS["PICO_DEVICE_NOT_FUNCTIONING"] = 0x00000144  # The device cannot be connected correctly
PICO_STATUS["PICO_INTERNAL_ERROR"] = 0x00000145  # The driver has experienced an unknown error and is unable to recover from this error
PICO_STATUS["PICO_MULTIPLE_DEVICES_FOUND"] = 0x00000146  # Used when opening units via IP and more than multiple units have the same ip address
PICO_STATUS["PICO_WARNING_NUMBER_OF_SEGMENTS_REDUCED"] = 0x00000147
PICO_STATUS["PICO_CAL_PINS_STATES"] = 0x00000148  # the calibration pin states argument is out of range
PICO_STATUS["PICO_CAL_PINS_FREQUENCY"] = 0x00000149  # the calibration pin frequency argument is out of range
PICO_STATUS["PICO_CAL_PINS_AMPLITUDE"] = 0x0000014A  # the calibration pin amplitude argument is out of range
PICO_STATUS["PICO_CAL_PINS_WAVETYPE"] = 0x0000014B  # the calibration pin wavetype argument is out of range
PICO_STATUS["PICO_CAL_PINS_OFFSET"] = 0x0000014C  # the calibration pin offset argument is out of range
PICO_STATUS["PICO_PROBE_FAULT"] = 0x0000014D  # the probe's identity has a problem
PICO_STATUS["PICO_PROBE_IDENTITY_UNKNOWN"] = 0x0000014E  # the probe has not been identified
PICO_STATUS["PICO_PROBE_POWER_DC_POWER_SUPPLY_REQUIRED"] = 0x0000014F  # enabling the probe would cause the device to exceed the allowable current limit
PICO_STATUS["PICO_PROBE_NOT_POWERED_WITH_DC_POWER_SUPPLY"] = 0x00000150  # the DC power supply is connected; enabling the probe would cause the device to exceed the allowable current limit
PICO_STATUS["PICO_PROBE_CONFIG_FAILURE"] = 0x00000151  # failed to complete probe configuration
PICO_STATUS["PICO_PROBE_INTERACTION_CALLBACK"] = 0x00000152  # failed to set the callback function, as currently in current callback function
PICO_STATUS["PICO_UNKNOWN_INTELLIGENT_PROBE"] = 0x00000153  # the probe has been verified but not known on this driver
PICO_STATUS["PICO_INTELLIGENT_PROBE_CORRUPT"] =	0x00000154  # the intelligent probe cannot be verified
PICO_STATUS["PICO_PROBE_COLLECTION_NOT_STARTED"] = 0x00000155  # the callback is null, probe collection will only start when first callback is a not a null pointer
PICO_STATUS["PICO_PROBE_POWER_CONSUMPTION_EXCEEDED"] = 0x00000156  # the current drawn by the probe(s) has exceeded the allowed limit
PICO_STATUS["PICO_WARNING_PROBE_CHANNEL_OUT_OF_SYNC"] = 0x00000157  # the channel range limits have changed due to connecting or disconnecting a probe the channel has been enabled
PICO_STATUS["PICO_DEVICE_TIME_STAMP_RESET"] = 0x01000000  # The time stamp per waveform segment has been reset.
PICO_STATUS["PICO_WATCHDOGTIMER"] = 0x10000000  # An internal erorr has occurred and a watchdog timer has been called.
PICO_STATUS["PICO_IPP_NOT_FOUND"] = 0x10000001  # The picoipp.dll has not been found.
PICO_STATUS["PICO_IPP_NO_FUNCTION"] = 0x10000002  # A function in the picoipp.dll does not exist.
PICO_STATUS["PICO_IPP_ERROR"] = 0x10000003  # The Pico IPP call has failed.
PICO_STATUS["PICO_SHADOW_CAL_NOT_AVAILABLE"] = 0x10000004  # Shadow calibration is not available on this device.
PICO_STATUS["PICO_SHADOW_CAL_DISABLED"] = 0x10000005  # Shadow calibration is currently disabled.
PICO_STATUS["PICO_SHADOW_CAL_ERROR"] = 0x10000006  # Shadow calibration error has occurred.
PICO_STATUS["PICO_SHADOW_CAL_CORRUPT"] = 0x10000007  # The shadow calibration is corrupt.
PICO_STATUS["PICO_DEVICE_MEMORY_OVERFLOW"] = 0x10000008  # the memory onboard the device has overflowed


def pico_tag(number):
    return PICO_STATUS.keys()[PICO_STATUS.values().index(number)]


def pico_num(tag):
    try:
        n = PICO_STATUS[tag]
    except KeyError:
        n = PICO_STATUS["PICO_NOT_USED"]
    return n


PICO_INFO = dict()
PICO_INFO["PICO_DRIVER_VERSION"] = 0x00000000
PICO_INFO["PICO_USB_VERSION"] = 0x00000001
PICO_INFO["PICO_HARDWARE_VERSION"] = 0x00000002
PICO_INFO["PICO_VARIANT_INFO"] = 0x00000003
PICO_INFO["PICO_BATCH_AND_SERIAL"] = 0x00000004
PICO_INFO["PICO_CAL_DATE"] = 0x00000005
PICO_INFO["PICO_KERNEL_VERSION"] = 0x00000006
PICO_INFO["PICO_DIGITAL_HARDWARE_VERSION"] = 0x00000007
PICO_INFO["PICO_ANALOGUE_HARDWARE_VERSION"] = 0x00000008
PICO_INFO["PICO_FIRMWARE_VERSION_1"] = 0x00000009
PICO_INFO["PICO_FIRMWARE_VERSION_2"] = 0x0000000A
PICO_INFO["PICO_MAC_ADDRESS"] = 0x0000000B
PICO_INFO["PICO_SHADOW_CAL"] = 0x0000000C
PICO_INFO["PICO_IPP_VERSION"] = 0x0000000D
